typedef struct {

	unsigned char *data;
	int datasize;
	int bytecount;

} EZArray;

typedef struct {

	int w, h;
	GLuint obj; // texture object generated by glGenTextures

} TextureGL;

typedef struct {

	GLuint vertex_array; // "VAO"
	uint vertex_count;

} MeshGL;

static const char *vertex3D =
"#version 150 core\n"
"uniform mat4 position_matrix;\n"
"uniform mat4 normal_matrix;\n"
"in vec3 position;\n"
"in vec3 normal;\n"
"in vec2 UV;\n"
"out vec3 normal_camera;\n"
"out vec2 frag_UV;\n"
"void main() {\n"
    "gl_Position = position_matrix * vec4(position.xyz, 1.0);\n" // get final position
    "normal_camera = (normal_matrix * vec4(normal, 1.0)).xyz;\n" // get final normal
    "frag_UV = UV;\n" // pass along UV
"}";

static const char *fragment3D =
"#version 150 core\n"
"uniform sampler2D tex;\n"
"in vec3 normal_camera;\n"
"in vec2 frag_UV;\n"
"out vec4 outColor;\n"
"void main() {\n"
	"float c = dot(normal_camera, vec3(0.436, 0.9, 0)) * 0.3 + 0.7;\n"
	"outColor = texture(tex, frag_UV) * vec4(c, c, c, 1.0);\n"
	"if (outColor.a == 0) { discard; }" // texture clip transparency
"}";

static GLuint shader3D_program;

// hardcoded values of near plane = 0.01, far plane = 100.0
#define PROJ_MATRIX(w, h, fov) (GLfloat[][4]) {\
    { h / (float) w / tan(fov * M_PI / 360.0), 0, 0, 0 },\
    { 0, 1.0 / tan(fov * M_PI / 360.0), 0, 0 },\
    { 0, 0, -1.00020002, -1.0 },\
    { 0, 0, -0.0200020002, 0 }\
}

static void append_ezarray(EZArray *array, void *data, int data_length) {

	if (!array->data) {

		// create a data allocation
		array->data = malloc(data_length * 8);
		array->datasize = data_length * 8;
		array->bytecount = 0;

	} else if (array->datasize < array->bytecount + data_length) {

		// increase the size of the data allocation
		array->data = realloc(array->data, (array->bytecount + data_length) * 2);
		array->datasize = (array->bytecount + data_length) * 2;
	}

	memcpy(array->data + array->bytecount, data, data_length);
	array->bytecount += data_length;
}

// array of textures Lua can register to
static TextureGL textures[100];
static int texture_count = 0;

static int create_texture(lua_State *state) {

	TextureGL *texture_gl = &textures[texture_count];

	SDL_Surface *surface = IMG_Load(luaL_checkstring(state, 1));
	
	texture_gl->w = surface->w;
	texture_gl->h = surface->h;

	// flip texture vertically to match OpenGL spec
	unsigned char *pixels = (unsigned char *) surface->pixels;
	int pixelBytes = surface->format->BytesPerPixel;

	for (int y = 0; y < surface->h / 2; y++) {

		for (int x = 0; x < surface->w; x++) {

			int top = x + y * surface->h;
			int bottom = x + (surface->w * surface->h - (y + 1) * surface->h);

			for (int i=0; i<pixelBytes; i++) {

				unsigned char hold = pixels[top * pixelBytes + i];
				pixels[top * pixelBytes + i] = pixels[bottom * pixelBytes + i];
				pixels[bottom * pixelBytes + i] = hold;
			}
		}
	}

	// create texture object
	glGenTextures(1, &texture_gl->obj);

	// bind texture (to active texture 2D)
	glBindTexture(GL_TEXTURE_2D, texture_gl->obj);

	// wrap repeat
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);

	// filter linear
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);

	// write texture data
	glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, surface->w, surface->h, 0, GL_RGBA, GL_UNSIGNED_BYTE, surface->pixels);

	// clean up
	SDL_FreeSurface(surface);

	// tell Lua what index to use to reference this texture
	lua_pushnumber(state, texture_count);
	texture_count++;

	return 1;
}

// array of meshes Lua can register to
static MeshGL meshes[100];
static int mesh_count = 0;

static int create_mesh_helper(const unsigned char *mesh_data, const int mesh_bytecount, const int mesh_vertcount) {

	// make vertex array
	GLuint vertex_array;
	glGenVertexArrays(1, &vertex_array);
	glBindVertexArray(vertex_array);

	// make vertex buffer (stored by vertex_array)
	GLuint vertex_buffer;
	glGenBuffers(1, &vertex_buffer);
	glBindBuffer(GL_ARRAY_BUFFER, vertex_buffer);								// make it the active buffer
	glBufferData(GL_ARRAY_BUFFER, mesh_bytecount, mesh_data, GL_STATIC_DRAW);	// copy vertex data into the active buffer

	// link active vertex data and shader attributes
	GLint pos_attrib = glGetAttribLocation(shader3D_program, "position");
	glVertexAttribPointer(pos_attrib, 3, GL_FLOAT, GL_FALSE, sizeof(float) * 8, 0);
	glEnableVertexAttribArray(pos_attrib); // requires a VAO to be bound

	GLint normal_attrib = glGetAttribLocation(shader3D_program, "normal");
	glVertexAttribPointer(normal_attrib, 3, GL_FLOAT, GL_FALSE, sizeof(float) * 8, (GLvoid *) (sizeof(float) * 3));
	glEnableVertexAttribArray(normal_attrib);

	GLint uv_attrib = glGetAttribLocation(shader3D_program, "UV");
	glVertexAttribPointer(uv_attrib, 2, GL_FLOAT, GL_FALSE, sizeof(float) * 8, (GLvoid *) (sizeof(float) * 6));
	glEnableVertexAttribArray(uv_attrib);

	// debind vertex array
	glBindVertexArray(0);

	// register mesh
	MeshGL *mesh_gl = &meshes[mesh_count];

	mesh_gl->vertex_array = vertex_array;
	mesh_gl->vertex_count = mesh_vertcount;

	return mesh_count++;
}

static int create_mesh(lua_State *state) {

	// read obj file
	FILE *file = fopen(luaL_checkstring(state, 1), "r");

	if (file == NULL) {
		printf("File \"%s\" does not exist!\n", luaL_checkstring(state, 1));
		exit(1);
	}

	char line[1024];

	EZArray position_data  = {0};
	EZArray normal_data    = {0};
	EZArray texture_data   = {0};
	EZArray composite_data = {0}; // stores combined vertex position, normal, and texture data

	int vertex_count;

	while (fgets(line, 1024, file)) {

		char prefix[8];

		sscanf(line, "%s", prefix);

		if (!strcmp(prefix, "v")) {

			float v[3];
			
			sscanf(line, "v %f %f %f", &v[0], &v[1], &v[2]);

			// obj vertices have reverse xz
			v[0] = -v[0];
			v[2] = -v[2];

			append_ezarray(&position_data, v, sizeof(float) * 3);
		}

		else if (!strcmp(prefix, "vn")) {

			float n[3];
			
			sscanf(line, "vn %f %f %f", &n[0], &n[1], &n[2]);

			// obj vertices have reverse xz
			n[0] = -n[0];
			n[2] = -n[2];

			append_ezarray(&normal_data, n, sizeof(float) * 3);
		}

		else if (!strcmp(prefix, "vt")) {

			float n[2];
			
			sscanf(line, "vt %f %f", &n[0], &n[1]);

			append_ezarray(&texture_data, n, sizeof(float) * 2);
		}

		else if (!strcmp(prefix, "f")) {

			// only works with tris right now (no quads or ngons)

			unsigned int p[3]; // vertex position indices
			unsigned int t[3]; // vertex texture coordinate indices
			unsigned int n[3]; // vertex normal indices
			
			sscanf(line, "f %u/%u/%u %u/%u/%u %u/%u/%u",
				&p[0], &t[0], &n[0],
				&p[1], &t[1], &n[1],
				&p[2], &t[2], &n[2]);

			// convert vertex indices to vertex positions (indices start at 1 for some reason)
			append_ezarray(&composite_data, position_data.data + ((p[0] - 1) * sizeof(float) * 3), sizeof(float) * 3);
			append_ezarray(&composite_data, normal_data.data +   ((n[0] - 1) * sizeof(float) * 3), sizeof(float) * 3);
			append_ezarray(&composite_data, texture_data.data +  ((t[0] - 1) * sizeof(float) * 2), sizeof(float) * 2);

			append_ezarray(&composite_data, position_data.data + ((p[1] - 1) * sizeof(float) * 3), sizeof(float) * 3);
			append_ezarray(&composite_data, normal_data.data +   ((n[1] - 1) * sizeof(float) * 3), sizeof(float) * 3);
			append_ezarray(&composite_data, texture_data.data +  ((t[1] - 1) * sizeof(float) * 2), sizeof(float) * 2);

			append_ezarray(&composite_data, position_data.data + ((p[2] - 1) * sizeof(float) * 3), sizeof(float) * 3);
			append_ezarray(&composite_data, normal_data.data +   ((n[2] - 1) * sizeof(float) * 3), sizeof(float) * 3);
			append_ezarray(&composite_data, texture_data.data +  ((t[2] - 1) * sizeof(float) * 2), sizeof(float) * 2);
			
			vertex_count += 3;
		}
	}

	fclose(file);

	// register mesh
	lua_pushnumber(state, create_mesh_helper(composite_data.data, composite_data.bytecount, vertex_count));

	return 1;
}

static void mat4_mult(const GLfloat b[4][4], const GLfloat a[4][4], GLfloat out[4][4]) {

	// a (rightmost) is applied first, then b

	GLfloat matrix[4][4] = {
		{
			a[0][0] * b[0][0] + a[0][1] * b[1][0] + a[0][2] * b[2][0] + a[0][3] * b[3][0],
			a[0][0] * b[0][1] + a[0][1] * b[1][1] + a[0][2] * b[2][1] + a[0][3] * b[3][1],
			a[0][0] * b[0][2] + a[0][1] * b[1][2] + a[0][2] * b[2][2] + a[0][3] * b[3][2],
			a[0][0] * b[0][3] + a[0][1] * b[1][3] + a[0][2] * b[2][3] + a[0][3] * b[3][3],
		},
		{
			a[1][0] * b[0][0] + a[1][1] * b[1][0] + a[1][2] * b[2][0] + a[1][3] * b[3][0],
			a[1][0] * b[0][1] + a[1][1] * b[1][1] + a[1][2] * b[2][1] + a[1][3] * b[3][1],
			a[1][0] * b[0][2] + a[1][1] * b[1][2] + a[1][2] * b[2][2] + a[1][3] * b[3][2],
			a[1][0] * b[0][3] + a[1][1] * b[1][3] + a[1][2] * b[2][3] + a[1][3] * b[3][3],
		},
		{
			a[2][0] * b[0][0] + a[2][1] * b[1][0] + a[2][2] * b[2][0] + a[2][3] * b[3][0],
			a[2][0] * b[0][1] + a[2][1] * b[1][1] + a[2][2] * b[2][1] + a[2][3] * b[3][1],
			a[2][0] * b[0][2] + a[2][1] * b[1][2] + a[2][2] * b[2][2] + a[2][3] * b[3][2],
			a[2][0] * b[0][3] + a[2][1] * b[1][3] + a[2][2] * b[2][3] + a[2][3] * b[3][3],
		},
		{
			a[3][0] * b[0][0] + a[3][1] * b[1][0] + a[3][2] * b[2][0] + a[3][3] * b[3][0],
			a[3][0] * b[0][1] + a[3][1] * b[1][1] + a[3][2] * b[2][1] + a[3][3] * b[3][1],
			a[3][0] * b[0][2] + a[3][1] * b[1][2] + a[3][2] * b[2][2] + a[3][3] * b[3][2],
			a[3][0] * b[0][3] + a[3][1] * b[1][3] + a[3][2] * b[2][3] + a[3][3] * b[3][3],
		},
	};

	int x, y;

	for (x = 0; x < 4; x++) {
		for (y = 0; y < 4; y++) {
			out[x][y] = matrix[x][y];
		}
	}
}

static void generate_rotation_matrices(GLfloat pitch_matrix[4][4], float pitch, GLfloat yaw_matrix[4][4], float yaw) {

	pitch_matrix[0][0] = 1;
	pitch_matrix[0][1] = 0;
	pitch_matrix[0][2] = 0;
	pitch_matrix[0][3] = 0;

	pitch_matrix[1][0] = 0;
	pitch_matrix[1][1] = cos(pitch);
	pitch_matrix[1][2] = -sin(pitch);
	pitch_matrix[1][3] = 0;

	pitch_matrix[2][0] = 0;
	pitch_matrix[2][1] = sin(pitch);
	pitch_matrix[2][2] = cos(pitch);
	pitch_matrix[2][3] = 0;

	pitch_matrix[3][0] = 0;
	pitch_matrix[3][1] = 0;
	pitch_matrix[3][2] = 0;
	pitch_matrix[3][3] = 1;

	yaw_matrix[0][0] = cos(yaw);
	yaw_matrix[0][1] = 0;
	yaw_matrix[0][2] = sin(yaw);
	yaw_matrix[0][3] = 0;

	yaw_matrix[1][0] = 0;
	yaw_matrix[1][1] = 1;
	yaw_matrix[1][2] = 0;
	yaw_matrix[1][3] = 0;

	yaw_matrix[2][0] = -sin(yaw);
	yaw_matrix[2][1] = 0;
	yaw_matrix[2][2] = cos(yaw);
	yaw_matrix[2][3] = 0;

	yaw_matrix[3][0] = 0;
	yaw_matrix[3][1] = 0;
	yaw_matrix[3][2] = 0;
	yaw_matrix[3][3] = 1;
}

static float camera_x, camera_y, camera_z;
static float camera_pitch, camera_yaw;

static int set_camera(lua_State *state) {

	camera_x     = luaL_checknumber(state, 1);
	camera_y     = luaL_checknumber(state, 2);
	camera_z     = luaL_checknumber(state, 3);
	camera_pitch = luaL_checknumber(state, 4);
	camera_yaw   = luaL_checknumber(state, 5);
}

// parameters: mesh, texture, model x y z pitch yaw
static int draw_mesh(lua_State *state) {

	MeshGL    *mesh_gl    = &meshes  [(int) luaL_checknumber(state, 1)];
	TextureGL *texture_gl = &textures[(int) luaL_checknumber(state, 2)];

	float model_x     = luaL_checknumber(state, 3);
	float model_y     = luaL_checknumber(state, 4);
	float model_z     = luaL_checknumber(state, 5);
	float model_pitch = luaL_checknumber(state, 6);
	float model_yaw   = luaL_checknumber(state, 7);

	// shared buffers
	GLfloat pitch_matrix[4][4];
	GLfloat yaw_matrix[4][4];

	GLfloat position_matrix[4][4];

	// bind the mesh's vertex mesh and texture
	glBindVertexArray(mesh_gl->vertex_array);
	glBindTexture(GL_TEXTURE_2D, texture_gl->obj);

	// model matrix (converts from model space to world space)
	generate_rotation_matrices(
		pitch_matrix, model_pitch,
		yaw_matrix, model_yaw
	);

	GLfloat model_matrix[4][4];

	mat4_mult(yaw_matrix, pitch_matrix, model_matrix); // rotation

	model_matrix[3][0] = model_x; // translation
	model_matrix[3][1] = model_y;
	model_matrix[3][2] = model_z;

	// view matrix (converts from world space to view space, aka accounts for camera transformations)
	// must apply translations before rotations this time, unlike model matrix!
	generate_rotation_matrices(
		pitch_matrix, -camera_pitch,
		yaw_matrix,   -camera_yaw
	);

	GLfloat view_matrix[4][4] = {
		{1, 0, 0, 0},
		{0, 1, 0, 0},
		{0, 0, 1, 0},
		{-camera_x, -camera_y, -camera_z, 1}
	};

	mat4_mult(yaw_matrix, view_matrix, view_matrix);
	mat4_mult(pitch_matrix, view_matrix, view_matrix);

	// final position matrix (PROJ_MATRIX * view_matrix * model_matrix)
	int w, h;
	SDL_GetWindowSize(window, &w, &h);

	mat4_mult(PROJ_MATRIX(w, h, 90), view_matrix, position_matrix);
	mat4_mult(position_matrix, model_matrix, position_matrix);

	// normal matrix (applied to normals to account for mesh rotation)
	GLfloat normal_matrix[4][4];

	generate_rotation_matrices(
		pitch_matrix, -model_pitch,
		yaw_matrix, -model_yaw
	);

	mat4_mult(yaw_matrix, pitch_matrix, normal_matrix);

	// load the 3D shader program and the uniforms we just calculated
	glUseProgram(shader3D_program);
	glUniformMatrix4fv(glGetUniformLocation(shader3D_program, "position_matrix"), 1, GL_FALSE, &position_matrix[0][0]);
	glUniformMatrix4fv(glGetUniformLocation(shader3D_program, "normal_matrix"), 1, GL_FALSE, &normal_matrix[0][0]);

	// draw
	glDrawArrays(GL_TRIANGLES, 0, mesh_gl->vertex_count);
}

static void create_shader_program(GLuint *const program_out, const char *vertex_code, const char *fragment_code) {

	*program_out = glCreateProgram();

	GLuint vertex_shader = glCreateShader(GL_VERTEX_SHADER);
	glShaderSource(vertex_shader, 1, (const char *const *) &vertex_code, NULL);
	glCompileShader(vertex_shader);
	glAttachShader(*program_out, vertex_shader);

	GLuint fragment_shader = glCreateShader(GL_FRAGMENT_SHADER);
	glShaderSource(fragment_shader, 1, (const char *const *) &fragment_code, NULL);
	glCompileShader(fragment_shader);
	glAttachShader(*program_out, fragment_shader);

	glLinkProgram(*program_out);
}